### ISSUE TITLE
Is this being used in prod?

### ISSUE THREAD

**Issue by khabinov** [dreyk/zraft_lib#19]
Hi Alexander,

Thanks a lot for putting so much effort into implementing RAFT in erlang. I'm very curious now if this lib is being used in prod currently? Well, there seems to be few other RAFT implementations listed here https://raftconsensus.github.io/, but apparently all of them besides this lib are neither up-to-date nor production ready.

Thanks!

**Comment by ongardie** [comment]
@khabinov, the table on the Raft website shows the date the row in the table was last updated, not when the code was last updated. There are several Raft implementations that are up-to-date and production ready (though I don't know about the Erlang implementations).

**Comment by khabinov** [comment]
Hi @ongardie,

Thanks for the RAFT itself. Well, I'm more interested in erlang implementations, and now I'm looking into this lib and into some PAXOS lib https://github.com/basho/riak_ensemble.

**Comment by dreyk** [comment]
Hi, Oleg.
Currently this library in pre production stage. It is used in one of our erlang project and  we have stated deliver it to our customer. Initially I was looking on risk-ensemble too, but found some conceptual and design issues.

**Comment by khabinov** [comment]
Thanks Alexander! I will close this issue.

P.S.: it seems that `riak_ensemble` is way more complicated than `zraft_lib` and also doesn't seem to support snapshots. Out of curiosity, what kind of issues did you find there?

**Comment by dreyk** [comment]
Oleg, Can send me your email? My email you can tske from one of the source file.
