### ISSUE TITLE
Why two metadata files?

### ISSUE THREAD

**Issue by cmeiklejohn** [dreyk/zraft_lib#22]
I'm a bit confused.

It appears that everywhere the metadata for Raft is written out, the update_metadata function is called twice with the same data -- this causes the version number to increment twice, and based on whether the version number modulo 2 is equal to zero, causes a different file to be read out.

This is not clearly documented, and it's unclear why this is happening and what the process is.  It also seems problematic, given a failure could occur in between the two file operations when one has synchronized and the other hasn't.

Why is this the case?

**Comment by dreyk** [comment]
It's for safety.If one of files has been lost or corrupted, then other meta file will be used. 
File(not currupted) this largest version used during initialisation process.

**Comment by cmeiklejohn** [comment]
It seems like a better decision is to have the function save both files, instead of ensuring that at every single call site remembering to invoke `update_metadata` twice, it's very unclear from an initial reading, without your explanation, why this is done.

**Comment by cmeiklejohn** [comment]
I think a better solution here would be to only write out a single file and use some sort of CRC (or similar mechanism) to detect file corruption.

**Comment by dreyk** [comment]
How will it prevent from lost meta file, that can be currupted on vm crash during write operation for example?

**Comment by dreyk** [comment]
Yes you are right about generalization function.

**Comment by cmeiklejohn** [comment]
| How will it prevent from lost meta file, that can be currupted on vm crash during write operation for example?

I guess my point here is that the mechanism is not very principled.  Why store the backup file in the same directory on the same filesystem?  Why not use 10 files?  Why not 20?  I think a more principled approach would be to store the state using some sort of error correction code and use a checksum that could detect, for instance, a bit flip or similar -- the existing mechanism won't protect against individual corruption in the file as long as it still convertible via Erlang term format.

**Comment by michaelklishin** [comment]
Writing to two files doesn't guarantee that no data was corrupted. In fact, if they are in the same directory, chances are, either no write will fail or both will. Calculating a checksum (e.g. CRC, as suggested by @cmeiklejohn) and verifying it on load is a better idea.

**Comment by ongardie** [comment]
LogCabin keeps two metadata files but only writes one per update (alternating). Each file has a checksum, and of the files with valid checksums on boot, the one with the largest version is used (https://github.com/logcabin/logcabin/blob/v1.1.0/Storage/SegmentedLog.cc#L377).

The idea is that you might have a crash/power loss while writing that corrupts the current file you're writing to, but then you can safely fall back to the other file on boot. Using 2 files is useful in that approach (but using 3 or more doesn't make sense).

Another approach people commonly take is to write to a temp file, fsync it, then rename() it to the file and fsync the directory (at least). I think that works too, though it may be less efficient.

**Comment by cmeiklejohn** [comment]
Would a PR be accepted to bring this in line with the LogCabin implementation by removing the second `update_metadata` call at the call sites?

**Comment by dreyk** [comment]
Yes. It will be accepted! Thank you

**Comment by cmeiklejohn** [comment]
Here's a PR:

https://github.com/dreyk/zraft_lib/pull/26
