### ISSUE TITLE
maybe_set_back_end race can prohibit startup

### ISSUE THREAD

**Issue by cmeiklejohn** [dreyk/zraft_lib#23]
`zraft_fs_log` is initialized with a peer name and writes out a file via `update_metadata` upon peer initialization; however, because the initialization of a peer and the updating of it's backend is asynchronous, if the cluster shuts down after initialization before `maybe_set_back_end` is called, which later triggers the `update_metadata` function, this can result in a peer's state on disk having an undefined backend.

Upon restart of the cluster, `zraft_lib` will be unable to make progress, given it attempts to call the init function, as part of the supervisor, on an undefined module.

See the initialization failure below:
```
20:57:53.421 [error] gen_server <0.347.0> terminated with reason: {'module could not be loaded',[{undefined,init,[{'group-1449176238392144-peer-1',nonode@nohost}],[]},{zraft_fsm,install_snapshot,1,[{file,"src/zraft_fsm.erl"},{line,730}]},{zraft_fsm,delayed_init,1,[{file,"src/zraft_fsm.erl"},{line,124}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,681}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
```

I believe the proper fix is to move the `maybe_set_back_end` function into the `zraft_fs_log` module, pass the backend from the initialization of `zraft_consensus`, and ensure the file is *never* persisted with an `undefined` backend, otherwise the system will fail to start in the future.

Let me know if you would like me to provide a PR of you think there is an alternative solution.

**Comment by benoitc** [comment]
bump
