### ISSUE TITLE
what's the point of the expiry_session callback?

### ISSUE THREAD

**Issue by videlalvaro** [dreyk/zraft_lib#4]
For what I see here you delete some keys from the dict backend, but what's the point of that? https://github.com/dreyk/zraft_lib/blob/master/src/zraft_dict_backend.erl#L64

**Comment by dreyk** [comment]
These Datas was written as temporary. (See apply_data/3 and zraft_session:write/4).
Expiration method is called from zraft_fsm after a session has been expired or failed.
Each peer expires sessions independatly based on heartbeat and global time(special field in entry messages is filled by  the leader). Or then leader detects session down( it monitors session) it will send special message to all peers to delete the session.

**Comment by videlalvaro** [comment]
So if my raft backend doesn't use temporary data, then I don't need to care about this callback?

**Comment by dreyk** [comment]
Yes you are right. Just return {ok,[],State}. If you don't use sessions it will be never called.

**Comment by videlalvaro** [comment]
Thanks
