### ISSUE TITLE
what's the point of the snapshot functions?

### ISSUE THREAD

**Issue by videlalvaro** [dreyk/zraft_lib#5]
Are the snapshots there also for sessions?

**Comment by dreyk** [comment]
No. Snapshot is used for log truncation and you must implement it.
If peer restart after long work it may be take a long time to reapply all logs, snaphot will help in this case.
See original Raft paper.
Currently snaphot will be took after each 1000 log entries. It's configurable.

**Comment by videlalvaro** [comment]
OK, but how can I take a snapshot just based on the state provided to the callback? https://github.com/dreyk/zraft_lib/blob/master/src/zraft_backend.erl#L52

I'd assue based on the `init/1` function here https://github.com/dreyk/zraft_lib/blob/master/src/zraft_backend.erl#L33 that `state()` is something that belongs to my app, that the raft implementation doesn't care about.

**Comment by dreyk** [comment]
You must persist  only you data(state) to directory provided in callback. All other work will be made by zraft_fsm and zraft_snaphot_writer modules. And you must implement intstall_snaphot to restore data from persistence storage.

**Comment by videlalvaro** [comment]
In my case I'm just using your library to synchronise calls to rabbitmq queues. The queues already take care of persistence, so, not sure what to do here…

**Comment by dreyk** [comment]
In theory if you implementation is pure functional, it's not nessary to write such function but in practice it's always false:) For example we use back ends based on eats tables and leveldb.

**Comment by videlalvaro** [comment]
Do you think you will ever provide those backend examples?

**Comment by dreyk** [comment]
These backends very specific to my private projects but I have plan to implement general  backend based on ets table that will be similar to zookeeper concept.

**Comment by dreyk** [comment]
If you don't need persiste data.
Then 
snapshot(State)->    {async,fun()->ok end, State}

**Comment by videlalvaro** [comment]
yup, that's what I did

**Comment by dreyk** [comment]
Can you explain more,  what do you do?

**Comment by videlalvaro** [comment]
I have this in my code `snapshot(State)-> {async,fun()->ok end, State}`.
