### ISSUE TITLE
zraft_fs_log:load_fs/1 will fail if PeerId starts with '/'

### ISSUE THREAD

**Issue by videlalvaro** [dreyk/zraft_lib#6]
According to the docs, if one of the Components passed to `filename:join/1` starts with a `/`, then all previous elements will be removed from the result. This means if I have a PeerId = "/something", then it will try to create a "/something" directory, which will fail due to lack of permissions.

Not sure if the user of the library should take care of this, or the raft library should escape characters that might be dangerous as part of file names

See: http://www.erlang.org/doc/man/filename.html#join-1

**Comment by dreyk** [comment]
PeerID declareted as atom and must be a atom. 
It isn't good idea to start atom from /., but it's possible in erlang.
Do you think any term in peerid will be useful?

**Comment by videlalvaro** [comment]
I need to have the "/" in the PeerId since to uniquely identify a rabbitmq queue inside a cluster, we need the vhost, which could be "/", plus the queue name, so what I'm doing is appending those.

At RabbitMQ we do this for example with file names: https://github.com/rabbitmq/rabbitmq-server/blob/master/src/rabbit_queue_index.erl#L542 which is what I ended up using.

Be aware that someone by accident might use '/' in the PeerId, which will might have the undesirable accident of destroying some files on their disk root folder

**Comment by michaelklishin** [comment]
Users can escape slashes as well. Using an atom for PeerID sounds reasonable.

**Comment by videlalvaro** [comment]
@michaelklishin the problem is not if they use atoms or not, the problem is that atoms, or whatever is used, cannot start with a `/`, even more, PeerId names shouldn't contain any `/` at all, since that would create sub folders.

I think the raft library should do some sort of hashing when creating folders, but not use whatever is directly provided by users of the library.

**Comment by dreyk** [comment]
Using hash for directory names or some escaping is possible. I will implement it next week  or you can make PR if you already have done it.

**Comment by videlalvaro** [comment]
I'll send you a PR then with something like what we have on RabbitMQ

**Comment by michaelklishin** [comment]
If having slashes also affects directory paths then I'm inclined to think that hashing directory names is a very good idea.
