### ISSUE TITLE
why the use of -include_lib("zraft_lib/include/zraft.hrl").

### ISSUE THREAD

**Issue by videlalvaro** [dreyk/zraft_lib#8]
Why do you use `-include_lib("zraft_lib/include/zraft.hrl").` in the code instead of `-include("zraft.hrl").` considering that `zraft.hrl` is a header local to your library?

**Comment by dreyk** [comment]
Only one reason. I used IDEA and It highlights "include" incorrect in multi erlang project mode. 
Do you know difference between include_lib and include?

**Comment by michaelklishin** [comment]
[include is local to your app](http://erlang.org/pipermail/erlang-questions/2009-July/045516.html). [Preprocessor docs](http://erlang.org/doc/reference_manual/macros.html) largely say the same thing.

**Comment by dreyk** [comment]
Yes I know. But there isn't difference in this case.

**Comment by videlalvaro** [comment]
So your IDEA plugin doesn't understand `-include("zraft.hrl").` ???

Anyway, as everything in code, it's not about the results we obtain, but the semantics. `include("zraft.hrl").` is there for cases when you include libraries from your own projects, that's the meaning it has.

Besides, compiling the library without rebar becomes a bit more complex, since the path `zraft_lib/include` doesn't exist on the project root folder.

**Comment by michaelklishin** [comment]
I'd report this to the IDEA Erlang plugin maintainers, they seem to be quite responsive. Using preprocessor features in a way they are not meant to be used to work around an IDE bug is a curious decision.

**Comment by dreyk** [comment]
It isn't dicision. It's old and maybe bad habit:)
As for IDEA. It can't find *.hrl in include directory then you import multiple  projecte as rebar deps.

**Comment by dreyk** [comment]
I will fix it after my holidays on Monday

**Comment by videlalvaro** [comment]
Cool, thanks
